# Generated by Django 4.2.6 on 2025-04-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening', models.IntegerField()),
                ('conversation_id', models.IntegerField()),
                ('conversation', models.JSONField()),
            ],
        ),
    ]
